### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [keithmathe/flashcards#2]
The following features are checked in the readme but **not shown in the GIF**. These user stories are not given points. Please record a new GIF and resubmit your assignment using the submit button in the course portal in order to get full points for the user story.

- User can cancel out of the creation screen

In order for us to count these towards your submission, please record another GIF that captures these features. Once you do, please push your updates and **submit your lab project again through the course portal so that we can regrade it**.

**Comment by keithmathe** [comment]
Noted! I've recorded a comprehensive GIF and pushed the code. I've also resubmitted on the course portal.
